### ISSUE TITLE
Makefile: use .d files

### ISSUE THREAD

**Issue by Myresa** [bad-zapple/libbad-zapple#4]
Use .d files

**Comment by touline-p** [comment]
Je vais plutot faire en sorte que le Makefile lance le CMake en lisant des fichier text qui contiendrai le nom des sources.

On pourra ettofer le makefile avec d'autre commande que cmake ne pourrais pas faire. ou alors lancer les test dans l'attente de voir si il y a une possibilite de passer par cmake
